version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.1-jdk

    working_directory: ~/custom-keycloak

    steps:
      - checkout
      - run:
          name: Clean & Package
          command: mvn clean package